on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
          check-latest: true
      - name: Test
        run: |
          go test ./...
